version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rag-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rag_platform
    networks:
      - rag-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app/backend
      - ./files:/app/files
      - backend_venv:/app/.venv
      - chroma_data:/app/backend/chroma_db
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=rag_platform
      - CORS_ORIGINS=*
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - rag-network
    healthcheck:
      test: curl -f http://localhost:8001/api/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    networks:
      - rag-network
    stdin_open: true
    tty: true

networks:
  rag-network:
    driver: bridge

volumes:
  mongodb_data:
  backend_venv:
  chroma_data:
